### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Anisha7** [MakeMeSenpai/MadLibs.py#1]
Great work on these challenges! Here's some feedback to further improve your code:
- You can challenge yourself by adding some tests for your code. Some questions to ask yourself when writing tests: Does it work as expected? What are different kinds of inputs users can put in? How would your program react to these? How do we want the program to handle such edge cases?
- Try adding a ReadMe describing what madlibs is and how to run your program and maybe even some screenshots with descriptions. Think about how you would explain this project to someone outside of Make School who doesn't have the context. 
- You can also try to handle invalid input (characters like - < > / ( * or numbers). What should be in the story if user types in an invalid word.

**Comment by The1stAnthony** [comment]
- made readme
